### ISSUE TITLE
Error installing Bugsnag from Homebrew

### ISSUE THREAD

**Issue by cole-cochran** [bugsnag/bugsnag-dsym-upload#46] opened 2020-09-09 16:29 UTC
Our CI/CD pipeline broke due to installing Bugsnag from homebrew as part of our dependencies. 

Error: Calling Non-checksummed download of bugsnag-dsym-upload formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):

It appears Bugsnag tap has been removed from Homebrew without any warning. 

Command used is directly from read me of this repository. 

brew install \ https://raw.github.com/bugsnag/bugsnag-upload/master/tools/homebrew/bugsnag-dsym-upload.rb

**Comment by steve-nester-uk** [comment] 2020-09-09 16:30
@cole-cochran thanks for raising, this is being looked at on issue: https://github.com/bugsnag/bugsnag-dsym-upload/issues/16, you can track progress there.  I will close this issue as a duplicate of 16.

**Closed by steve-nester-uk** 2020-09-09 16:30 UTC

**Comment by xander-jones** [comment] 2020-09-10 11:56
@cole-cochran We've moved this formula to a Homebrew tap 🎉​ .

If you have previously installed the bugsnag-dsym-upload tool, uninstall it with
```
$ brew uninstall bugsnag-dsym-upload
```

Clean up your local Homebrew area with
```
$ brew cleanup
```

Then, you can install `bugsnag-dsym-upload` with:
```
$ brew install bugsnag/tap/bugsnag-dsym-upload
```

This will also add the Bugsnag tap, so that any updates to the dSYM upload tool can be downloaded through Homebrew directly in future.

**Comment by trinadhkoya** [comment] 2020-09-10 12:01
Thanks @xander-jones .
